[package]
name = "dbg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.26", features = ["derive"] }
env_logger = "0.11.5"
gimli = "0.31.1"
libc = "0.2.167"
log = "0.4.22"
memmap2 = "0.9.5"
object = "0.36.5"
shlex = "1.3.0"
typed-arena = "2.0.2"
