name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install rust tools
      run: rustup component add rustfmt clippy

    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build

    - name: Run unit tests
      run: cargo test

    - name: Run e2e tests
      run: |
        python -m pip install pytest pytest-timeout pytest-xdist
        pytest --timeout=10 -n auto tests
