name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: cargo build

    - name: Run unit tests
      run: cargo test

    - name: Run e2e tests
      run: |
        python -m pip install pytest pytest-timeout
        pytest --timeout=10 tests
